export const SET_TOKEN = "SET_TOKEN"
export const AUTH_FETCH_LOADING = "AUTH_FETCH_LOADING"
export const AUTH_FETCH_SUCCESS = "AUTH_FETCH_SUCCESS"
export const AUTH_FETCH_FAILURE = "AUTH_FETCH_FAILURE"

export const SET_FILTERED_USERS = "SET_FILTERED_USERS"
export const USERS_FETCH_LOADING = "USERS_FETCH_LOADING"
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS"
export const USERS_FETCH_FAILURE = "USERS_FETCH_FAILURE"

export const USER_CLEAR = "USER_CLEAR"
export const USER_FETCH_LOADING = "USER_FETCH_LOADING"
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS"
export const USER_FETCH_FAILURE = "USER_FETCH_FAILURE"
